apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "spot-termination-exporter.shortname" . }}-config-loader
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade 
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "spot-termination-exporter.fullname" . }}-config-loader
      containers:
      - name: {{ template "spot-termination-exporter.shortname" . }}-config-loader 
        image: 817276302724.dkr.ecr.eu-west-1.amazonaws.com/infra/k8s-config-loader:v2.1
        imagePullPolicy: Always
        env:
        - name: APP
          value: {{ template "spot-termination-exporter.name" . }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ required "Undefined configloader.aws_access_key_id" .Values.configloader.aws_access_key_id }}
        - name: AWS_SECRET_ACCESS_KEY 
          valueFrom:
            secretKeyRef:
              name: {{ template "spot-termination-exporter.fullname" . }}-preload
              key: AWS_SECRET_ACCESS_KEY 
        - name: CONFIGMAP_RESOURCE_NAME
          value: {{ template "spot-termination-exporter.fullname" . }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: PREFIX
          value: {{ .Values.configloader.prefix | quote }}
        - name: RELEASE
          value: {{ .Release.Name }}
        - name: RELEASE_REVISION
          value: {{ .Release.Revision | quote }}
        - name: SECRET_RESOURCE_NAME
          value: {{ template "spot-termination-exporter.fullname" . }}
      restartPolicy: OnFailure
  backoffLimit: 4
