apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spot-termination-exporter.fullname" . }}-preload
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "spot-termination-exporter.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback 
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- if .Values.configmap }}
{{ toYaml .Values.configmap | indent 2 }}
{{- end }}
