---
# TODO Implement proper roles
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    labels:
      app: {{ template "spot-termination-exporter.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
    name: {{ template "spot-termination-exporter.fullname" . }}
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: {{ template "spot-termination-exporter.fullname" . }} 
    labels:
      app: {{ template "spot-termination-exporter.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  subjects:
    - kind: ServiceAccount
      name: {{ template "spot-termination-exporter.fullname" . }}
      namespace: {{ .Release.Namespace }}
  roleRef:
    kind: ClusterRole 
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: {{ template "spot-termination-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "spot-termination-exporter.fullname" . }}-config-loader
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: {{ template "spot-termination-exporter.fullname" . }}-config-loader
  labels:
    app: {{ template "spot-termination-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "spot-termination-exporter.fullname" . }}-config-loader
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io 
