apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spot-termination-exporter.fullname" . }}-preload
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  AWS_SECRET_ACCESS_KEY: {{ .Values.configloader.aws_secret_access_key | b64enc | quote }}
