version: '2.3'

services:
  spot-termination-exporter:
    build: .
    image: 817276302724.dkr.ecr.eu-west-1.amazonaws.com/infra/spot-termination-exporter${DOCKER_TAG}
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - ENVIRONMENT
    ports:
      - 8080
